[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "pyedge"
version = "0.1.0"
description = "edge file reader for python"

[tool.setuptools]
packages = ["pyedge"]
